### PR TITLE
Adding DuckDuckGo

### PR DESCRIPTION
**Pull request by thgpdr**

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@thgpdr thanks for contributing ps do followme and it will be merged after i resolve the conflicts in your PR

**Comment by thgpdr** [comment]
Done ;)

**Comment by Ishaan28malik** [comment]
there are some conflicts pls chk them and refer to the updated repo once and make the same changes done @thgpdr

**Review by Ishaan28malik — APPROVED** [review]
Thanks for this

**Comment by Ishaan28malik** [comment]
@thgpdr thanks for the contribution sorry for late merging i didn't get time to resolve the issue 
Keep contributing and please do follow me thanks  💯

**Pull request merged**
