### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by adeonir**
Add my name and profile link.

### CODE REVIEW

**Review by Ishaan28malik — CHANGES_REQUESTED** [review]
There are some conflicts 
Please have a look

**Comment by Ishaan28malik** [comment]
@adeonir   thanks for making your first contribution, I will be merging your Pull Request, also look at the issues so that you can get a chance to win a limited community Swag from me.

If you like the project and Repo please give it a **star** and **Follow** me on Github (would be appreciated)

**Comment by adeonir** [comment]
@Ishaan28malik conflict has been resolved!

**Review by Ishaan28malik — APPROVED** [review]

**Comment by Ishaan28malik** [comment]
@adeonir   thanks for making your first contribution, I will be merging your Pull Request, also look at the issues so that you can get a chance to win a limited community Swag from me.

If you like the project and Repo please give it a **star** and **Follow** me on Github (would be appreciated)

**Pull request merged**
