### PR TITLE
CHANGED DOWN SIDE OF PAGE #MAJOR CHNAGES ADDED NEW CSS - by mohit

### PR DESCRIPTION
**Pull request by mbcse**
i have changed odd looking panel in downside ,added some new css like card ,row ,etc!

### CODE REVIEW

**Review by Ishaan28malik — CHANGES_REQUESTED** [review]
There are some conflicts

**Comment by mbcse** [comment]
> There are some conflicts

resolved

**Comment by Ishaan28malik** [comment]
@mbcse thanks for contributing.

**Review by Ishaan28malik — APPROVED** [review]

**Comment by mbcse** [comment]
My contribution is comming invalid ,can you help me with that

**Comment by Ishaan28malik** [comment]
@mbcse Yup since they are no longer accepting the PRs

**Pull request merged**
