### PR TITLE
edited

### PR DESCRIPTION
**Pull request by computerwala**
thanks

### CODE REVIEW

**Review by Ishaan28malik — CHANGES_REQUESTED** [review]
Please add your name instead of a username

**Comment by Ishaan28malik** [comment]
@computerwala  thanks for making your first contribution, I will be merging your Pull Request, also look at the issues so that you can get a chance to win a limited community Swag from me.

If you like the project and Repo please give it a **star** and **Follow** me on Github (would be appreciated)

**Comment by computerwala** [comment]
-Updated my name with username
-beautify the code 
-added one open source project

**Comment by Ishaan28malik** [comment]
@computerwala  try this year for Hacktoberfest and have a look at the updated repo and contribute.
## HAPPY HACKING

**Pull request closed without merging**
