### PR TITLE
Added Gautam Arora

### PR DESCRIPTION
**Pull request by Gautam-Arora24**
Kindly check @Ishaan28malik

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@Gautam-Arora24 also add resources to the Resources Folder and you are done

**Review by Gautam-Arora24 — COMMENTED** [review]
Added my name and Awesome youtube channel links

**Comment by Ishaan28malik** [comment]
@Gautam-Arora24 good work , keep contributing.

**Comment by Gautam-Arora24** [comment]
Thanks @Ishaan28malik . I will keep contributing :)

**Pull request merged**
