### PR TITLE
Update Index.html

### PR DESCRIPTION
**Pull request by ayoolafelix**
I've added my name and GitHub link, in order to connect with other open-source enthusiasts. Hit me up at http://www.twitter.com/ayoolafelix, http://www.instagram.com/ayoolafelix

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
Thnx for contributing @ayoolafelix  make sure you follow me and star this repo so that you don't miss the updates and contribute during Hacktoberfest 2020.
Also resolve the conflicts.

**Comment by ayoolafelix** [comment]
How do I resolve the conflicts?

**Comment by Ishaan28malik** [comment]
@ayoolafelix Click on Resolve conflicts and then it will show you what was added after your commit just edit that part again.

**Review by ayoolafelix — COMMENTED** [review]
Great

**Comment by Ishaan28malik** [comment]
Also there has been some update, go through them and make a new PR

**Pull request closed without merging**
