### PR TITLE
Just added my name

### PR DESCRIPTION
**Pull request by eduard-caraiman**
Hello there! I just added my name on the list. Happy HackToberFest!!!

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@TigerAsH94 pls star this repo and follow me it will merge

**Comment by eduard-caraiman** [comment]
@Ishaan28malik  Done

**Review by Ishaan28malik — APPROVED** [review]
You can contribute this year aswell

**Comment by Ishaan28malik** [comment]
@TigerAsH94   thanks for making your first contribution, I will be merging your Pull Request, also look at the issues so that you can get a chance to win a limited community Swag from me.

If you like the project and Repo please give it a **star** and **Follow** me on Github (would be appreciated).

**Pull request closed without merging**
