### PR TITLE
Added Gautam Arora in index.html

### PR DESCRIPTION
**Pull request by Gautam-Arora24**

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
Thnx for contributing @Gautam-Arora24  remake sure u star this repo so that you don't miss the updates and contribute during Hacktoberfest 2020.
Also, resolve the conflicts.

**Comment by Gautam-Arora24** [comment]
Kindly check @Ishaan28malik

**Comment by Ishaan28malik** [comment]
@Gautam-Arora24 there are some updates, go through the Readme again and then make a new PR

**Comment by Gautam-Arora24** [comment]
Ok :)

**Pull request closed without merging**
