### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by codernuub**

### CODE REVIEW

**Review by Ishaan28malik — CHANGES_REQUESTED** [review]
Resolve the conflicts

**Comment by codernuub** [comment]
But where

**Comment by codernuub** [comment]
Done

**Comment by Ishaan28malik** [comment]
@codernuub  thnx for contributing , try this year aswell with updated repo and make sure to follow me and star this repo so that you don't miss updates regarding the new changes and issues during Hacktoberfest 2020.

**Pull request closed without merging**
